IU/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IU.Controllers
{
    public class ContatoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string nome, string email, string telefone, string cidade, string uf, string assunto,
            string observacoes)
        {
            return View();
        }
    
     
    }
}

IU/Controllers/DicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IU.Controllers
{
    public class DicasController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    
     
    }
}

IU/Controllers/LoginController.cs
using Alphanet.Acesso.Aplicacao;
using Alphanet.Acesso.Aplicacao.Data;
using IU.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlphaNet.PassagemAerea.IU.Controllers
{
    public class LoginController : AbstractController
    {
        [HttpPost]
        public ActionResult Login(AutenticarUsuarioComando comando)
        {
            AutenticacaoAplicacaoService autenticacaoAplicacaoService = new AutenticacaoAplicacaoService();

            UsuarioData data = autenticacaoAplicacaoService.autenticar(comando);

            if (data != null)
            {
                Session["login"] = data.login;
                Session["nome"] = data.nome;
                Session["email"] = data.email;
                Session["gestor"] = this.usuarioLogadoGestor();
                Session["papel"] = this.usuarioPapel();
            } else
                TempData["msgAutenticacao"] = "Falha no login";

            return RedirectToAction("Index", "Home");            
            
        }
        [HttpPost]
        public ActionResult LoginNovaReserva(string login, string senha, string vooId)
        {
            AutenticacaoAplicacaoService autenticacaoAplicacaoService = new AutenticacaoAplicacaoService();
            AutenticarUsuarioComando comando = new AutenticarUsuarioComando(login,senha);

            UsuarioData data = autenticacaoAplicacaoService.autenticar(comando);

            if (data != null)
            {
                TempData["vooId"] = vooId;

                Session["login"] = data.login;
                Session["nome"] = data.nome;
                Session["email"] = data.email;
                Session["gestor"] = this.usuarioLogadoGestor();
                Session["papel"] = this.usuarioPapel();
            }
            else
                TempData["msgAutenticacao"] = "Falha no login";

            return RedirectToAction("NovaReservaPessoal", "Voo");

        }
        [HttpPost]
        public ActionResult Logoff()
        {
            Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult registrarNovoUsuario() {
            if (this.usuarioEstaLogado())
                return RedirectToAction("Index", "Home");

            return View("RegistrarNovoUsuario");
        }
        [HttpPost]
        public ActionResult registrarNovoUsuario(RegistrarNovoUsuarioComando comando)
        {
            AcessoAplicacaoService acessoAplicacaoService = new AcessoAplicacaoService();

            acessoAplicacaoService.registrarNovoUsuario(comando);

            this.colocarNaSessao(comando.login, comando.nome, comando.email, comando.papel == "Gestor", "Usuario");
            return RedirectToAction("Index", "Home");
        }
        private void colocarNaSessao(string login, string nome, string email, bool gestor,string papel)
        {            
            Session["login"] = login;
            Session["nome"] = nome;
            Session["email"] = email;
            Session["gestor"] = gestor;
            Session["papel"] = papel;
        }
    }
}

IU/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlphaNet.PassagemAerea.Aplicacao.Avioes;
using RazorPDF;
using AlphaNet.PassagemAerea.Domain.Model;

namespace IU.Controllers
{
    public class RelatorioController : AbstractController
    {

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Clientes()
        {
            return new PdfResult(DominioRegistro.clienteService().todosClientes(), "Clientes");
        }
        public ActionResult Avioes()
        {
            return new PdfResult(DominioRegistro.aplicacaoAviaoService().todosAvioes(), "Avioes");
        }
        public ActionResult Cidades()
        {
            return new PdfResult(DominioRegistro.cidadeService().todasCidades(), "Cidades");
        }
        public ActionResult Ticket(string clienteId="",string vooId="")
        {
            List<AlphaNet.PassagemAerea.Aplicacao.Voos.Data.VooReservaData> dados = new List<AlphaNet.PassagemAerea.Aplicacao.Voos.Data.VooReservaData>();

            foreach (AlphaNet.PassagemAerea.Aplicacao.Voos.Data.VooReservaData reserva in DominioRegistro.vooService().todasReservas())
                dados.Add(reserva);

            return new PdfResult(dados, "Ticket");
        }

    }
}

IU/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Alphanet</title>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jqueryui")
        
        @Styles.Render("~/Content/extjs")
        @Scripts.Render("~/bundles/extjs")


<script type="text/javascript">


    function mostrar() {
        document.getElementById('resultado').style.visibility = true;
    }
</script>


    </head>

    <body >
        <div id="container">
        <div id="top">
        <div id="logo"><a href="@Url.Action("Index","Home")"><img src="/Content/themes/base/images/logo_fca.png" alt="Alphanet" border="0" ></a></div>
        <div id="f-login">
            <div class="form-login"> 
                @if (Session["login"]!=null){
                   <p> @Html.Label("Você está logado com usuário " + Session["login"]+"("+Session["papel"]+")")</p>
                    <form name="form1" method="post" action="@Url.Action("Logoff","Login")">                
              
                           <input type="submit" name="Logoff" value="Sair">
                              
                                @if (Session["papel"].Equals("Gestor") || Session["papel"].Equals("Atendente"))
                                {                                 
                                   @Html.ActionLink("Área Administrativa","Index","Voo") 
                                }
                             </form>
            
                }else{
                    <form name="form1" method="post" action="@Url.Action("Login","Login")">
                        <ul>
                            <li> <label>Login: <input name="login" type="text" size="4"></label>  </li>
                            <li> <label>Senha: <input name="senha" type="password" size="4"></label></li>
                            <li> <input type="submit" name="Login" value="OK"> <br /></li> 
                           @* <li><br />@Html.ActionLink("Cadastre-se","RegistrarNovoUsuario","Login")</li> *@
                        </ul>
                </form>
            
                }
            </div>  
        </div>
        </div>
            
           <div id="nav">


        <div class="botao">@Html.ActionLink("HOME","Index","Home")</div>
        <div class="botao">@Html.ActionLink("INSTITUCIONAL","Index","Institucional")</div>
        <div class="botao">@Html.ActionLink("VOE JÁ","IndexPessoal","Voo")</div>
        <div class="botao">@Html.ActionLink("MINHAS RESERVAS","MostrarReservasClienteLogado","Voo")</div>
        <div class="botao">@Html.ActionLink("CADASTRE-SE","RegistrarNovoUsuario","Login")</div>
        <div class="botao">@Html.ActionLink("DICAS","Index","Dicas")</div>
        <div class="botao">@Html.ActionLink("CONTATO","Index","Contato")</div>

        </div> 
            

            @RenderBody()
            @RenderSection("scripts", required: false)

        <div id="rodape">
        <div id="desenvolvimento"><img src="/Content/themes/base/images/desenvolvimento.png" ></div>
        <div id="direitos">Todos os Direitos Reservados</div>
        <div id="facebook"><a href="#"><img src="/Content/themes/base/images/bt_facebook.png" border="0"></a></div>
        <div id="twitter"><a href="#"><img src="/Content/themes/base/images/bt_twitter.png" border="0"></a></div>
        <div id="youtube"><a href="#"><img src="/Content/themes/base/images/btyoutube.png" border="0"></a></div>
        </div>
            </div>
    </body>
</html>

IU/Views/Shared/_Layout_adm.cshtml
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Alphanet</title>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-2.1.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/jqueryui")

        @Styles.Render("~/Content/extjs")
        @Scripts.Render("~/bundles/extjs")
    </head>
    <body>

        <div id="container">
        <div id="top-adm">

        <div id="logo_adm"><img src="/Content/themes/base/images/logo_fca.png" alt="Alphanet" border="0" ></div>

            
 
                <div id="topo-login">
                     <div class="form-login-adm"> 
                            @if (Session["login"]!=null){
                                @Html.Label("Usuário: " + Session["login"]+"("+Session["papel"]+")") 
                                <form name="form1" method="post" action="@Url.Action("Logoff","Login")">
                                 <p>  <input type="submit" name="Logoff" value="Sair"></p> 
                                   <p> @Html.ActionLink("Público","Index","Home")</p>
                                </form>          
                            }

                           </div>

                      </div>
             <div id="fca">Área Administrativa</div>

            </div>
        
        
        <div id="nav">

        <div class="botao-adm">@Html.ActionLink("VOO","Index","Voo")</div>
        <div class="botao-adm">@Html.ActionLink("USUÁRIO","Index","Usuario")</div>
        <div class="botao-adm">@Html.ActionLink("AVIÃO","Index","Aviao")</div>
        <div class="botao-adm">@Html.ActionLink("CLIENTE","Index","Cliente")</div>
        <div class="botao-adm">@Html.ActionLink("CIDADE","Index","Cidade")</div>
        <div class="botao-adm">@Html.ActionLink("RELATÓRIOS","Index","Relatorio")</div>
        </div>
    
         <div id="conteudo">

        <div id="conteudo-central">

            @RenderBody()

        </div>
        </div>            
            @RenderSection("scripts", required: false)
     

        <div id="rodape-adm">
        <div id="desenvolvimento"><img src="/Content/themes/base/images/desenvolvimento.png" ></div>
        <div id="rodape-adm-texto">Todos os Direitos Reservados</div>
         </div>


            </div>
    </body>
</html>